workflows:
  vless-workflow:
    name: Build VLESS APK
    max_build_duration: 30
    environment:
      vars:
        CM_BUILD_NUMBER: $BUILD_NUMBER
    scripts:
      # Переходим в папку android и делаем gradlew исполняемым
      - cd android && chmod +x gradlew
      # Возвращаемся в корень и запускаем сборку Flutter-проекта
      - cd .. && flutter build apk --debug
    artifacts:
      # Путь к готовому APK для Flutter-проекта
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - washingtonfizcl@gmail.com
