name: flutter_vless
description: Flutter plugin to run VLESS/VMESS as a local proxy and VPN on Android and iOS. V2Ray/Xray core. Shadowsocks, Trojan, Socks 5 support.

version: 1.0.1
homepage: https://github.com/XIIIFOX/flutter_vless/
tags:
     - VLESS
     - v2ray
     - xray
     - proxy
     - vpn
     - VMESS

topics:
  - vpn
  - vless
  - v2ray
  - xray
  - proxy
  - vmess

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.github.tfox.flutter_vless
        pluginClass: FlutterV2rayPlugin
      ios:
        pluginClass: FlutterVlessPlugin

  